import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Devices from "../components/ui/Devices/Devices";

// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout Component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
        style={{
          margin: "0",
          padding: "0",
          height: "100vh",
          width: "100vw",
          overflow: "hidden",
          position: "relative",
          backgroundColor: "#0a0a0a",
        }}
      >
        {/* Fullscreen SVG Background */}
        <img
          src="/Wall.svg"
          alt="Background"
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            objectFit: "fill",
            display: "block",
            zIndex: -1,
            pointerEvents: "none",
            userSelect: "none",
          }}
          draggable={false}
        />

        {/* App Content */}
        <Devices>{children}</Devices>
      </body>
    </html>
  );
}
