name: Build Docker Image

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: set_tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            TAG="latest"
          elif [[ "${GITHUB_REF}" == refs/pull/* ]]; then
            PR_NUMBER=$(echo "${GITHUB_REF}" | grep -oP 'refs/pull/\K[0-9]+')
            TAG="pr-${PR_NUMBER}"
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            TAG="${BRANCH_NAME//\//-}"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push multi-arch Docker image
        run: |
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/upayanmazumder/upayan.dev:${{ env.TAG }} \
            --build-arg NODE_ENV=production \
            --push
